### ISSUE TITLE
Doesn't work with unsaved documents

### ISSUE THREAD

**Issue by simonwhitaker** [jbree/InsertLine.novaextension#1] opened 2020-10-01 21:31 UTC
Thanks, this is a great extension! But I noticed it doesn't work in documents that haven't been saved yet.

Steps to reproduce:

1. In Nova, press CMD+N to start a new document
2. Type some text, then press CMD+Enter

Expected result: A new line is added after the current line, and the cursor moves to the start of the new line

Actual result: Nothing happens in the UI, I get an alert sound.

**Comment by jbree** [comment] 2020-10-01 21:47
Thanks for the report! Glad you're enjoying it.

I'm having trouble reproducing this issue locally.

One known issue is that the "Insert Line After" doesn't properly move the cursor when operating on the last line of the document (which in your case may also be the first). What I see is that a newline is created below the current line, but the cursor is moved to the end of that line rather than to the beginning of the created newline. Can you double check that that's not the case?

The fact that you get an alert sound seems to contradict my hypothesis, though. If this is not the issue, perhaps you could try performing the command from the command palette (cmd-shift-p, then select "insert line after") to try to narrow down the problem.

**Comment by simonwhitaker** [comment] 2020-10-02 08:51
Ah interesting... it looks like the extension doesn't even load for unsaved documents. I don't get an "insert line after" option in the command palette. If I save the file (or open a file from disk) the extension works fine.

Screencast: https://youtu.be/_gyfZFgbE5k

And to confirm my setup:

- Nove 1.2 (build 207005)
- Insert Line 1.2
- No other extensions enabled

Hope this helps!

**Comment by jbree** [comment] 2020-10-02 13:59
Thanks, the screencast was helpful. It looks like you have your Default Syntax set to "Plain text" in Preferences > Editor > Syntax, and the plugin is not being loaded in that situation.

I'm now able to reproduce the problem.

I tested out some other command extensions (DuplicateText, Hard Wrap) and discovered that they also fail to load on a new plaintext document. So, it looks like this may be a Nova issue. I'll send in a report.

**Comment by jbree** [comment] 2020-10-08 18:35
I received confirmation from Panic that this is indeed a Nova issue which should be fixed in v1.3.

**Closed as completed by jbree** 2020-10-08 18:35 UTC
